import uuid
from datetime import date, datetime
from decimal import Decimal
from typing import TYPE_CHECKING

from sqlalchemy import Date, DateTime, ForeignKey, Index, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.core.db_types import DecimalText
from app.core.enums import TXN_SOURCES, TXN_TYPES  # noqa: F401  (re-exported)

if TYPE_CHECKING:
    from app.models.lot_alloc import LotAlloc
    from app.models.txn_audit import TxnAudit


class Transaction(Base):
    __tablename__ = "transaction"
    __table_args__ = (
        Index("idx_txn_account_instrument_date", "account_id", "instrument_id", "date"),
        Index("idx_txn_date", "date"),
        Index("idx_txn_type", "txn_type"),
        Index("idx_txn_trade_pair", "trade_pair_id"),
        Index("idx_txn_deleted_at", "deleted_at"),
        Index("idx_txn_reconciliation", "reconciliation_id"),
    )

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    account_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("account.id"), nullable=False
    )
    instrument_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("instrument.id"), nullable=False
    )
    txn_type: Mapped[str] = mapped_column(String, nullable=False)  # buy/sell/spend/yield/adjustment

    # Trade date (not settlement). DATE type — timezone-naive by design.
    date: Mapped[date] = mapped_column(Date, nullable=False)

    # Quantity: NUMERIC(36,18) covers all crypto (18 decimals = wei-level precision)
    # Positive for buy/yield/upward-adjustment; negative for sell/downward-adjustment
    quantity: Mapped[Decimal] = mapped_column(DecimalText, nullable=False)

    # unit_price: price per unit in price_currency at time of trade; NULL for yield txns
    # NUMERIC(20,8): fiat precision sufficient for equity prices
    unit_price: Mapped[Decimal | None] = mapped_column(
        DecimalText, nullable=True
    )

    price_currency: Mapped[str | None] = mapped_column(String(10), nullable=True)

    # fx_rate_to_eur: EUR/price_currency rate LOCKED at trade date — never recomputed at query time
    # This is the critical FX-locking column. NUMERIC(20,10) for enough precision on FX rates.
    fx_rate_to_eur: Mapped[Decimal | None] = mapped_column(
        DecimalText, nullable=True
    )

    # cost_basis_eur: pre-computed = quantity × unit_price / fx_rate_to_eur
    # Stored as a denormalized column for fast portfolio reads
    cost_basis_eur: Mapped[Decimal | None] = mapped_column(
        DecimalText, nullable=True
    )

    # fee_eur: brokerage fee in EUR (converted at trade date FX)
    fee_eur: Mapped[Decimal] = mapped_column(
        DecimalText, nullable=False, default=Decimal("0")
    )

    notes: Mapped[str | None] = mapped_column(String, nullable=True)
    source: Mapped[str] = mapped_column(String, nullable=False, default="manual")
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    trade_pair_id: Mapped[str | None] = mapped_column(String(36), nullable=True)

    # Set for yield transactions generated by accrual cron
    apy_config_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("apy_config.id"), nullable=True
    )

    # Set on every adjustment txn produced by reconciliation Accept/Dismiss
    # AND on real txns produced by the Reject drawer; FK provides the
    # structural audit linkage.
    reconciliation_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("reconciliation.id"), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now(), onupdate=func.now()
    )

    # Relationship to lot_alloc rows for sell transactions.
    # Must be declared here so selectinload(Transaction.lot_allocs)
    # works as soon as the model is imported. cascade + passive_deletes work with the
    # ON DELETE CASCADE FK on lot_alloc.sell_txn_id.
    lot_allocs: Mapped[list["LotAlloc"]] = relationship(
        "LotAlloc",
        foreign_keys="[LotAlloc.sell_txn_id]",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )
    audits: Mapped[list["TxnAudit"]] = relationship(
        "TxnAudit",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )
