import * as React from "react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { cn } from "@/lib/utils";

export interface ActionBannerProps {
  /** ARIA live-region role. Default "status" (polite). */
  role?: "status" | "alert" | "note";
  /** Optional direct-child SVG icon. Shadcn Alert's [&>svg]:size-4 selector sizes it. */
  icon?: React.ReactNode;
  /** Banner title — short label (e.g. "Auto-generated by daily APY accrual"). */
  title: string;
  /** Banner body prose. ReactNode so callers can pass multi-line / formatted content. */
  body: React.ReactNode;
  /** Optional action slot — by convention a single shadcn `<Button>`. */
  action?: React.ReactNode;
  /** Optional className override forwarded to the underlying Alert root. */
  className?: string;
}

/**
 * ActionBanner — composition wrapper over shadcn Alert.
 *
 * Overrides the default role="alert" (assertive) to role="status" (polite) so the
 * banner does not interrupt assistive technology users. Non-dismissible by design
 * (no X button, no onDismiss prop).
 */
export function ActionBanner({
  role = "status",
  icon,
  title,
  body,
  action,
  className,
}: ActionBannerProps) {
  return (
    <Alert role={role} className={cn(className)}>
      {icon}
      <AlertTitle>{title}</AlertTitle>
      <AlertDescription>
        <p>{body}</p>
        {action ? <div className="mt-2">{action}</div> : null}
      </AlertDescription>
    </Alert>
  );
}
