import { test, expect } from "@playwright/test";
import { seedMultiAccountEth } from "./fixtures/seed-multi-account-eth";

/**
 * Integration test: multi-account-same-instrument ActionBanner deep-link.
 *
 * Scenario:
 *   - ETH has TWO APY configs: Revolut Earn (2.37%) and Cold Wallet (4%)
 *   - An auto-accrual yield row is tied to Revolut Earn + ETH
 *   - The test clicks Edit on that yield row → EditTxnDialog ActionBanner appears
 *   - Clicking "Edit APY source" MUST deep-link to Revolut Earn (NOT Cold Wallet)
 *
 * Pre-requisites for running:
 *   1. Dev compose stack: docker compose -f compose.yml -f compose.dev.yml up -d
 *   2. PW_APP_PASSWORD env var set to the same value as APP_PASSWORD in .env
 *      (or APP_PASSWORD is exported in the shell running the test)
 *
 * Run: cd frontend && npm run test:e2e -- apy-deep-link
 * Headed: cd frontend && npm run test:e2e:headed -- apy-deep-link
 */

// Password is read from env, never hardcoded.
const APP_PASSWORD = process.env.PW_APP_PASSWORD ?? process.env.APP_PASSWORD ?? "";

test.describe("auto-accrual yield ActionBanner deep-link", () => {
  test("lands on the correct account row (Revolut Earn, not Cold Wallet)", async ({
    page,
    request,
  }) => {
    if (!APP_PASSWORD) {
      throw new Error(
        "PW_APP_PASSWORD (or APP_PASSWORD) env var is not set. " +
          "Export it before running e2e tests: export PW_APP_PASSWORD=<your-password>",
      );
    }

    // ── 1. Seed the multi-account fixture via API ──────────────────────────────
    const seed = await seedMultiAccountEth(request, APP_PASSWORD);

    // ── 2. Authenticate the browser context ───────────────────────────────────
    //    The `request` fixture and `page` fixture have separate cookie jars, so
    //    we need to log in via the browser too.
    await page.goto("/login");
    await page.getByLabel(/password/i).fill(APP_PASSWORD);
    await page.getByRole("button", { name: /sign in/i }).click();
    // Middleware redirects / → /track after login.
    await expect(page).toHaveURL(/\/track/, { timeout: 10_000 });

    // ── 3. Navigate to /activity and find the seeded auto-accrual yield row ───
    await page.goto("/activity");
    // The yield row's notes cell renders the prefix "auto-accrual" as a Badge
    // and the remainder "2.37% APY" as a sibling <span> — no whitespace text
    // node between them, so the row's textContent is `auto-accrual2.37% APY`
    // (no space). hasText normalizes whitespace but cannot inject a missing
    // separator, so we anchor on the contiguous suffix "2.37% APY" + ETH +
    // Revolut Earn (unique to the seeded row even if other auto-accrual rows
    // exist).
    // TxnList is virtualized, so accept both role="row" div
     // rows and legacy <tr> elements. Scroll until the row materializes.
    const buildYieldRow = () => page
      .locator('[role="row"], tr')
      .filter({ hasText: "2.37% APY" })
      .filter({ hasText: "Revolut Earn" })
      .filter({ hasText: "ETH" })
      .first();
    let yieldRow = buildYieldRow();
    for (let attempt = 0; attempt < 25; attempt++) {
      if ((await yieldRow.count()) > 0) {
        try {
          await yieldRow.scrollIntoViewIfNeeded({ timeout: 1_000 });
          break;
        } catch {
          // fall through to scroll-and-retry
        }
      }
      await page.evaluate(() => window.scrollBy(0, window.innerHeight * 0.8));
      await page.waitForTimeout(120);
      yieldRow = buildYieldRow();
    }
    await expect(yieldRow).toBeVisible({ timeout: 10_000 });

    // ── 4. Click Edit on the yield row ────────────────────────────────────────
    await yieldRow.getByRole("button", { name: /edit transaction/i }).click();

    // ── 5. Verify the EditTxnDialog opened with the correct read-only state ───
    // Dialog title for auto-accrual yield is "Yield details".
    await expect(page.getByRole("heading", { name: "Yield details" })).toBeVisible();
    // ActionBanner title and body (verbatim copy).
    await expect(
      page.getByText("Auto-generated by daily APY accrual"),
    ).toBeVisible();
    await expect(
      page.getByText(/This transaction was created by the daily APY-accrual job/),
    ).toBeVisible();

    // ── 6. Click the "Edit APY source" banner button ───────────────────────────
    // The button text is "Edit APY source" followed by an ArrowRight icon (aria-hidden).
    // Playwright's getByRole matches the accessible name, which is the text node only.
    await page.getByRole("button", { name: /edit apy source/i }).click();

    // ── 7. Assert the URL matches the locked deep-link contract ────────────────
    // Expected: /holdings/i/<ETH-id>?tab=apy&account=<Revolut-Earn-id>
    await expect(page).toHaveURL(
      new RegExp(
        `/holdings/i/${seed.ethId}\\?tab=apy&account=${seed.revolutEarnAccountId}`,
      ),
      { timeout: 10_000 },
    );

    // ── 8. Assert the pulsed row is Revolut Earn (NOT Cold Wallet) ─────────────
    // data-pulse="true" is set transiently (~1.5s CSS animation).
    // We assert visibility with a short polling window to catch it before it clears.
    const pulsedRow = page.locator('[data-pulse="true"]').first();
    await expect(pulsedRow).toBeVisible({ timeout: 2_000 });
    await expect(pulsedRow).toContainText("Revolut Earn");
    await expect(pulsedRow).not.toContainText("Cold Wallet");

    // ── 9. Assert the ApyConfigForm Account Select pre-selects Revolut Earn ────
    // The Select trigger shows the account name when defaultValues.account_id is
    // set from the ?account= query param.
    // Use the first combobox (the Account select is the leading field in the form).
    await expect(
      page.getByRole("combobox").first(),
    ).toContainText("Revolut Earn", { timeout: 5_000 });
  });
});
