"""baseline schema (squashed 0001-0007)

Single clean baseline replacing the original seven incremental migrations.
Collapsed while the project had no production data to preserve (only the local
dev DB with disposable fake transactions). Captures the EXACT schema the seven
migrations produced — including the CHECK constraints, named FKs and server
defaults the ORM models do not declare, and money columns as canonical TEXT
(DecimalText) rather than NUMERIC — plus the one seed row migration 0003
inserted (user_setting concentration_threshold=0.25).

Generated by replaying the DDL of a fully-migrated empty database, so a fresh
build is byte-identical to what the old chain produced. Future schema changes
add new migrations chained from this baseline; never edit it once real data
exists.

Revision ID: baseline
Revises:
Create Date: 2026-06-13
"""
from __future__ import annotations

from alembic import op

revision = "baseline"
down_revision = None
branch_labels = None
depends_on = None

# Exact DDL captured from the fully-migrated (0001->0007) schema. Tables first
# (SQLite permits forward FK references at CREATE time), then indexes.
_DDL: list[str] = [
    "CREATE TABLE account (\n\tid VARCHAR(36) NOT NULL, \n\tname VARCHAR NOT NULL, \n\taccount_type VARCHAR NOT NULL, \n\tis_banked BOOLEAN DEFAULT '1' NOT NULL, \n\tcurrency VARCHAR(10) DEFAULT 'EUR' NOT NULL, \n\tcreated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (name)\n)",
    'CREATE TABLE tag (\n\tid VARCHAR(36) NOT NULL, \n\tname VARCHAR NOT NULL, \n\tcolor VARCHAR(20), \n\tPRIMARY KEY (id), \n\tUNIQUE (name)\n)',
    'CREATE TABLE holding_tag (\n\taccount_id VARCHAR(36) NOT NULL, \n\tinstrument_id VARCHAR(36) NOT NULL, \n\ttag_id VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (account_id, instrument_id, tag_id), \n\tFOREIGN KEY(account_id) REFERENCES account (id), \n\tFOREIGN KEY(instrument_id) REFERENCES instrument (id), \n\tFOREIGN KEY(tag_id) REFERENCES tag (id)\n)',
    "CREATE TABLE job_runs (\n\tid VARCHAR(36) NOT NULL, \n\tjob_name VARCHAR NOT NULL, \n\trun_date DATE NOT NULL, \n\tstarted_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tcompleted_at DATETIME, \n\tstatus VARCHAR DEFAULT 'running' NOT NULL, \n\tnotes VARCHAR, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_job_runs_name_date UNIQUE (job_name, run_date)\n)",
    'CREATE TABLE "instrument" (\n\tid VARCHAR(36) NOT NULL, \n\tsymbol VARCHAR NOT NULL, \n\tname VARCHAR NOT NULL, \n\tinstrument_type VARCHAR NOT NULL, \n\tbase_currency VARCHAR(10) NOT NULL, \n\tprice_source VARCHAR DEFAULT \'na\' NOT NULL, \n\tticker_override VARCHAR, \n\tcreated_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL, \n\trisk_level VARCHAR NOT NULL, display_decimals INTEGER, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_instrument_risk_level CHECK (risk_level IN (\'High\', \'Medium\', \'Low\', \'Liquid\')), \n\tUNIQUE (symbol, instrument_type)\n)',
    'CREATE TABLE txn_audit (\n\tid VARCHAR(36) NOT NULL, \n\ttransaction_id VARCHAR(36) NOT NULL, \n\tevent_type VARCHAR NOT NULL, \n\tchanged_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tchanged_fields JSON NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_txn_audit_event_type CHECK (event_type IN (\'edit\', \'delete\')), \n\tFOREIGN KEY(transaction_id) REFERENCES "transaction" (id) ON DELETE CASCADE\n)',
    'CREATE TABLE user_setting (\n\t"key" VARCHAR NOT NULL, \n\tvalue VARCHAR NOT NULL, \n\tupdated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY ("key")\n)',
    'CREATE TABLE concentration_mute (\n\tinstrument_id VARCHAR(36) NOT NULL, \n\tcreated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (instrument_id), \n\tFOREIGN KEY(instrument_id) REFERENCES instrument (id)\n)',
    'CREATE TABLE reconciliation (\n\tid VARCHAR(36) NOT NULL, \n\taccount_id VARCHAR(36) NOT NULL, \n\tsnapshot_date DATE NOT NULL, \n\tcreated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tnotes VARCHAR, \n\tholdings_snapshot JSON NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(account_id) REFERENCES account (id)\n)',
    'CREATE TABLE "transaction" (\n\tid VARCHAR(36) NOT NULL, \n\taccount_id VARCHAR(36) NOT NULL, \n\tinstrument_id VARCHAR(36) NOT NULL, \n\ttxn_type VARCHAR NOT NULL, \n\tdate DATE NOT NULL, \n\tprice_currency VARCHAR(10), \n\tnotes VARCHAR, \n\tsource VARCHAR DEFAULT \'manual\' NOT NULL, \n\tapy_config_id VARCHAR(36), \n\tcreated_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL, \n\tupdated_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL, \n\tdeleted_at DATETIME, \n\ttrade_pair_id VARCHAR(36), \n\treconciliation_id VARCHAR(36), \n\tquantity VARCHAR NOT NULL, \n\tunit_price VARCHAR, \n\tfx_rate_to_eur VARCHAR, \n\tcost_basis_eur VARCHAR, \n\tfee_eur VARCHAR DEFAULT \'0\' NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_txn_type_enum CHECK (txn_type IN (\'buy\', \'sell\', \'spend\', \'yield\', \'adjustment\')), \n\tCONSTRAINT fk_txn_reconciliation FOREIGN KEY(reconciliation_id) REFERENCES reconciliation (id), \n\tCONSTRAINT ck_txn_trade_pair_required CHECK ((txn_type = \'sell\' AND trade_pair_id IS NOT NULL) OR (txn_type = \'spend\' AND trade_pair_id IS NULL) OR (txn_type NOT IN (\'sell\', \'spend\'))), \n\tFOREIGN KEY(account_id) REFERENCES account (id), \n\tFOREIGN KEY(instrument_id) REFERENCES instrument (id), \n\tFOREIGN KEY(apy_config_id) REFERENCES apy_config (id)\n)',
    'CREATE TABLE "lot_alloc" (\n\tid VARCHAR(36) NOT NULL, \n\tsell_txn_id VARCHAR(36) NOT NULL, \n\tbuy_txn_id VARCHAR(36) NOT NULL, \n\tcreated_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL, \n\tquantity VARCHAR NOT NULL, \n\trealized_gain_eur VARCHAR, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(sell_txn_id) REFERENCES "transaction" (id) ON DELETE CASCADE, \n\tFOREIGN KEY(buy_txn_id) REFERENCES "transaction" (id)\n)',
    'CREATE TABLE "price_quote" (\n\tid VARCHAR(36) NOT NULL, \n\tinstrument_id VARCHAR(36) NOT NULL, \n\tdate DATE NOT NULL, \n\tcurrency VARCHAR(10) NOT NULL, \n\tsource VARCHAR NOT NULL, \n\tfetched_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL, \n\tprice VARCHAR NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_price_quote_inst_date_source UNIQUE (instrument_id, date, source), \n\tFOREIGN KEY(instrument_id) REFERENCES instrument (id)\n)',
    'CREATE TABLE "fx_rate" (\n\tid VARCHAR(36) NOT NULL, \n\tdate DATE NOT NULL, \n\tbase_currency VARCHAR(10) NOT NULL, \n\tquote_currency VARCHAR(10) NOT NULL, \n\tsource VARCHAR NOT NULL, \n\tfetched_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL, \n\trate VARCHAR NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_fx_rate_date_pair UNIQUE (date, base_currency, quote_currency)\n)',
    'CREATE TABLE "apy_config" (\n\tid VARCHAR(36) NOT NULL, \n\taccount_id VARCHAR(36) NOT NULL, \n\tinstrument_id VARCHAR(36) NOT NULL, \n\teffective_from DATE NOT NULL, \n\teffective_to DATE, \n\tcompounding VARCHAR DEFAULT \'daily_simple\' NOT NULL, \n\tcreated_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL, \n\tapy_rate VARCHAR NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (account_id, instrument_id, effective_from), \n\tFOREIGN KEY(instrument_id) REFERENCES instrument (id), \n\tFOREIGN KEY(account_id) REFERENCES account (id)\n)',
    'CREATE INDEX idx_txn_audit_transaction ON txn_audit (transaction_id)',
    'CREATE INDEX idx_reconciliation_account_date ON reconciliation (account_id, snapshot_date)',
    'CREATE INDEX idx_txn_date ON "transaction" (date)',
    'CREATE INDEX idx_txn_trade_pair ON "transaction" (trade_pair_id)',
    'CREATE INDEX idx_txn_deleted_at ON "transaction" (deleted_at)',
    'CREATE INDEX idx_txn_type ON "transaction" (txn_type)',
    'CREATE INDEX idx_txn_account_instrument_date ON "transaction" (account_id, instrument_id, date)',
    'CREATE INDEX idx_txn_reconciliation ON "transaction" (reconciliation_id)',
    'CREATE INDEX idx_lot_alloc_buy ON lot_alloc (buy_txn_id)',
    'CREATE INDEX idx_lot_alloc_sell ON lot_alloc (sell_txn_id)',
    'CREATE INDEX idx_price_quote_instrument_date ON price_quote (instrument_id, date)',
    'CREATE INDEX idx_fx_rate_date ON fx_rate (date)',
]

# Seed row that migration 0003 inserted; the app reads this default.
_SEED = "INSERT INTO user_setting (key, value) VALUES ('concentration_threshold', '0.25')"


def upgrade() -> None:
    for stmt in _DDL:
        op.execute(stmt)
    op.execute(_SEED)


def downgrade() -> None:
    raise NotImplementedError("baseline migration — nothing below it to downgrade to")
